[package]
name = "changelog-checker"
version = "1.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
colored = "3.1.1"
lexopt = "0.3.1"
reqwest = { version = "0.13.1", features = ["json", "blocking", "rustls"], default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
