[package]
name = "changelog-checker"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
colored = "2.1.0"
lexopt = "0.3.0"
reqwest = { version = "0.12.4", features = ["json", "blocking", "rustls-tls"], default-features = false }
serde = { version = "1.0.199", features = ["derive"] }
